#!/usr/bin/python3

import shutil
import subprocess
import os

thistuple = shutil.disk_usage("/x")

# fssource = thistuple[1]
fssource = shutil.disk_usage("/x")[1]
fsdestin = subprocess.check_output(['du', '-sb', '/home/scarwolf/machome']).split()[0].decode('utf-8')
# print(fssource)
# print(fsdestin)

numfss = int(fssource)
numfsd = int(fsdestin)

percentage = 100*(numfsd/numfss)

print("%9d of %9d completed.\n %3.2f%%" % (numfsd, numfss, percentage))






